#!/bin/bash
#SBATCH -C cpu
#SBATCH -q debug
#SBATCH -t 00:01:30
#SBATCH -N 1
#SBATCH -J TT_DPP_TT
#SBATCH --ntasks-per-node=64
#SBATCH --output=out.out 
#SBATCH --error=err.out 

module load vasp/5.4.4-cpu
export VASP_PP_PATH=/global/common/sw/cray/cnl7/mic_knl/vasp/pseudopotentials/PBE/
export ASE_VASP_VDW=/global/common/sw/cray/cnl7/mic_knl/vasp/vdw_kernal/

module load parallel

my_parallel="parallel --delay .2 -j $SLURM_NTASKS"
my_srun="srun --export=all --exclusive -n 32 -c 4"
my_srun="$my_srun --cpu-bind=cores"


# Run VASP in parallel across three folders
$my_parallel "$my_srun bash submit.sh" ::: {300..301}
